### ISSUE TITLE
Can bulkRNA-seq data be used to call background T-to-C substitutions ?

### ISSUE THREAD

**Issue by pigraul** [wulabupenn/scNT-seq#2]
Hi,

Can bulkRNA-seq be used to call background T-to-C substitutions? Or must be scRNA-seq data.

Thanks,
raulee

**Comment by Xiaojieqiu** [comment]
@pigraul you can do that too. Please check our highly optimized and parallelized dynast package: https://github.com/aristoteleo/dynast-release

**Comment by pigraul** [comment]
Thank you @Xiaojieqiu !  I have tried dynast ~~
